import { officialNames,reproductionRecipes,mixingEngine,classification,official,rgb } from './test/production-mixing-utils.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function mix(record, recipe, waterLevel=record.waterLevel){const sum=recipe.reduce((s,r)=>s+r.ratio,0);const sources=new Map(recipe.filter(r=>r.ratio>0).map(r=>[r.hex,r.ratio/sum]));return mixingEngine.mixAggregate({total:1,sources,waterLevel:clamp(waterLevel,0,1),mixLevel:1}).map(Math.round)}
function variants(record){const out=[];for(let i=0;i<record.recipe.length;i++)for(const pct of [-.1,.1]){const recipe=record.recipe.map((r,j)=>({...r,ratio:r.ratio*(j===i?1+pct:1)}));out.push({label:`${record.recipe[i].name} ${pct>0?'+':''}10%`,recipe,water:record.waterLevel})}for(const delta of [-.05,.05])out.push({label:`water ${delta>0?'+':''}${delta.toFixed(2)}`,recipe:record.recipe,water:record.waterLevel+delta});return out}
function nonDistance(p){if(!p)return false;const t=p.target,c=p.candidate;if(p.deltaE>5.5)return false;if(t.chroma<=8&&c.chroma>12)return false;if(t.chroma>12&&c.chroma<8)return false;if(p.chromaDelta>16)return false;if(t.chroma>8&&c.chroma>8){const maxC=Math.max(c.chroma,t.chroma),lim=maxC>=50?10:maxC>=30?14:18;if(p.hueDelta>lim)return false;}return true}
const centers=official.map(e=>({name:e.name,rgb:rgb(e.hex)}));
function ownership(c){const arr=centers.map(x=>{const dr=c[0]-x.rgb[0],dg=c[1]-x.rgb[1],db=c[2]-x.rgb[2];return {...x,d:Math.hypot(dr,dg,db)}}).sort((a,b)=>a.d-b.d);return {first:arr[0],second:arr[1],margin:arr[1].d-arr[0].d,ratio:arr[1].d/(arr[0].d||1e-9)}}
const samples=[];
for(const expected of officialNames){const rec=reproductionRecipes[expected];for(const v of variants(rec)){const c=mix(rec,v.recipe,v.water);const current=classification.nearestStrictOfficialRGB(...c).entry?.name??null;const near=classification.nearestOfficialEncyclopediaRGB(...c);const strict=classification.nearestStrictOfficialRGB(...c);const own=ownership(c);samples.push({expected,label:v.label,c,current,nearest:near.entry?.name,p:near.perception,adaptive:Number(strict.perception?.adaptiveRadius??0),margin:own.margin,ratio:own.ratio});}}
const slacks=[.25,.5,.75,1,1.25,1.5,2,2.5]; const margins=[0,.25,.5,.75,1,1.5,2,2.5,3,4,5,6,8,10,12]; const ratios=[1,1.02,1.05,1.08,1.1,1.15,1.2,1.3,1.4,1.5,1.75,2];
let best=[];
for(const slack of slacks)for(const minMargin of margins)for(const minRatio of ratios){let rescued=0,newWrong=0;for(const s of samples){if(s.current!==null)continue;const allowed=Math.min(7.5+slack,s.adaptive+slack);const ok=nonDistance(s.p)&&s.p.rgbDistance<=allowed&&s.margin>=minMargin&&s.ratio>=minRatio;if(!ok)continue;if(s.nearest===s.expected)rescued++;else newWrong++;}if(newWrong===0&&rescued>0)best.push({slack,minMargin,minRatio,rescued});}
best.sort((a,b)=>b.rescued-a.rescued||a.slack-b.slack||a.minMargin-b.minMargin);
console.log(JSON.stringify({best:best.slice(0,30), nulls:samples.filter(s=>s.current===null).length},null,2));
